Algoritmo "EX04"

// Declaração das variáveis
Var
   x, y, som: inteiro  // Valores a serem somados e resultado

Inicio

   // Lê o valor de X
   escreva("# Digite o valor de X: ")
   leia(x)

   // Lê o valor de Y
   escreva("# Digite o valor de Y: ")
   leia(y)

   // Calcula a soma de X e Y
   som <- (x + y)

   // Exibe a soma
   escreval("# Soma = ", som)

Fimalgoritmo
