Algoritmo "EX03"

// Declaração da variável
Var
   pass: inteiro  // Senha

Inicio

   // Solicita a senha
   escreva("# Digite a senha: ")
   leia(pass)

   // Repete até a senha ser correta
   enquanto (pass <> 2002) faca
      escreva("# Senha invalida! Tente novamente: ")
      leia(pass)
   fimenquanto

   // Senha correta, acesso permitido
   escreval("# Acesso permitido!")

Fimalgoritmo
