Algoritmo "EX10"

// Variáveis para contagem e valor de X
Var
   i, x: inteiro

Inicio

   // Solicita o valor de X
   escreva("# Digite o valor de X: ")
   
   // Lê o valor de X
   leia(x)

   // Loop de 1 até X
   para i de 1 ate x faca
   
      // Verifica se i é ímpar
      se (i mod 2 <> 0) entao

         // Imprime o valor ímpar
         escreval("# X: ", i)
      fimse
   fimpara

Fimalgoritmo
